title = "Rust Wasm Tech"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = "At Rust Wasm Tech, we are passionate about exploring the intersection of Rust programming and WebAssembly (Wasm) technology. Our goal is to provide insightful articles, tutorials, and resources to help you navigate the exciting landscape of Rust and Wasm."
index_site_pages = ["blog"]

[extra]
copyright = "rust-wasm.tech"
github = "https://github.com/bharattech"

date_style = "%B %e, %Y"
